{% set version = "2.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-svglite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/svglite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/svglite/svglite_{{ version }}.tar.gz
  sha256: 48700169eec1b05dbee9e2bae000aa84c544617b018cb3ac431a128cfd8dac56

build:
  number: 1
  merge_build_host: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - r-systemfonts >=1.0.0        # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cpp11
    - r-systemfonts >=1.0.0
    - libpng                       # [not win]
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-systemfonts >=1.0.0

test:
  commands:
    - $R -e "library('svglite')"           # [not win]
    - "\"%R%\" -e \"library('svglite')\""  # [win]

about:
  home: https://svglite.r-lib.org
  dev_url: https://github.com/r-lib/svglite
  doc_url: https://svglite.r-lib.org/reference/index.html
  license: GPL-2.0-or-later
  summary: A graphics device for R that produces 'Scalable Vector Graphics'. 'svglite' is a fork of the older 'RSvgDevice' package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
